#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
sudo touch /var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid
trap "echo I hate the kill command; sudo rm /var/run/holbertonscript.pid" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "sudo rm /var/run/holbertonscript.pid" SIGQUIT
while :
do
	echo "To infinity and beyond"
    sleep 2
done
