#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
echo $$ > /var/run/holbertonscript.pid
trap "echo  I hate the kill command " SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm -r /var/run/holbertonscript.pid" SIGQUIT
do
	echo "To infinity and beyond"
    sleep 2
done
