#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
file='/var/run/holbertonscript.pid'
sudo touch $file
echo $$ > $file
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "sudo rm $file" SIGQUIT
while :
do
	echo "To infinity and beyond"
    sleep 2
done
