#!/usr/bin/env bash
# Basic while loop
i=1
while [ $i -le 11 ];
do
    if [ $i == 4 ]; then
        echo "bad luck"
    elif [ $i == 8 ]; then
        echo "good luck"
    else
        echo "Hoberthon School"
    fi
    let "i++"
done
